#!/bin/bash
cd /sys/kernel/config/usb_gadget/
mkdir -p isticktoit
cd isticktoit
# disable gadget
echo "" > UDC
# remove functions
rm configs/*.*/*
# remove configuration string directories
rmdir configs/*/strings/*
# remove configurations
rmdir configs/*
# remove functions (modules aren't unloaded)
rmdir functions/*
# remove gadget string directories
rmdir strings/*
# remove gadget
cd ..
rmdir isticktoit
